swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api
paths:
  /student/:
    get:
      tags:
      - student
      description: get Student
      operationId: StudentController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Student'
        "403":
          description: ""
    post:
      tags:
      - student
      description: create Student
      operationId: StudentController.Post
      parameters:
      - in: body
        name: body
        description: body for Student content
        required: true
        schema:
          $ref: '#/definitions/models.Student'
      responses:
        "201":
          description: '{int} models.Student'
        "403":
          description: body is empty
  /student/{id}:
    get:
      tags:
      - student
      description: get Student by id
      operationId: StudentController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Student'
        "403":
          description: :id is empty
    put:
      tags:
      - student
      description: update the Student
      operationId: StudentController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Student content
        required: true
        schema:
          $ref: '#/definitions/models.Student'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Student'
        "403":
          description: :id is not int
    delete:
      tags:
      - student
      description: delete the Student
      operationId: StudentController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Student:
    title: Student
    type: object
    properties:
      BirthDate:
        type: string
      Cpf:
        type: string
      Email:
        type: string
      Id:
        type: integer
        format: int64
      Name:
        type: string
      Phone:
        type: string
tags:
- name: student
  description: |2
     StudentController operations for Student
